chore: storybook build

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -3,7 +3,9 @@ pipeline {
 
     environment {
         DOCKER_IMAGE_NAME = 'thenext/the-next-client'
+        DOCKER_STORYBOOK_IMAGE_NAME = 'thenext/the-next-client-storybook'
         CONTAINER_NAME = 'the-next-client'
+        STORYBOOK_CONTAINER_NAME = 'the-next-client-storybook'
         GITHUB_CREDENTIALS_ID = 'bonjin-github'
     }
 
@@ -18,26 +20,56 @@ pipeline {
         }
 
         stage('Dockerizing') {
-            steps {
-                sh "echo Image Build Start"
-                sh "docker build . -t ${DOCKER_IMAGE_NAME}"
-            }
-            post {
-                success {
-                    sh 'echo "Build Docker Image Success"'
-                }
+            parallel {
+                stage('Build Client Image') {
+                    steps {
+                        sh "echo Image Build Start"
+                        sh "docker build --target app . -t ${DOCKER_IMAGE_NAME}"
+                    }
+                    post {
+                        success {
+                            sh 'echo "Build Docker Image Success"'
+                        }
 
-                failure {
-                    sh 'echo "Build Docker Image Fail"'
+                        failure {
+                            sh 'echo "Build Docker Image Fail"'
+                        }
+                    }
+                }
+                stage('Build Storybook Image') {
+                    steps {
+                        sh "echo Storybook Image Build Start"
+                        sh "docker build --target storybook . -t ${DOCKER_STORYBOOK_IMAGE_NAME}"
+                    }
+                    post {
+                        success {
+                            sh 'echo "Build Storybook Docker Image Success"'
+                        }
+
+                        failure {
+                            sh 'echo "Build Storybook Docker Image Fail"'
+                        }
+                    }
                 }
             }
         }
 
         stage('Deploy') {
-            steps {
-                echo 'Deploy Start'
-                sh "docker stop ${CONTAINER_NAME} || true && docker rm ${CONTAINER_NAME} || true"
-                sh "docker run -d --name ${CONTAINER_NAME} -p 3080:80 ${DOCKER_IMAGE_NAME}"
+            parallel {
+                stage('Deploy Client') {
+                    steps {
+                        echo 'Deploy Start'
+                        sh "docker stop ${CONTAINER_NAME} || true && docker rm ${CONTAINER_NAME} || true"
+                        sh "docker run -d --name ${CONTAINER_NAME} -p 3080:80 ${DOCKER_IMAGE_NAME}"
+                    }
+                }
+                stage('Deploy Storybook') {
+                    steps {
+                        echo 'Deploy Storybook Start'
+                        sh "docker stop ${STORYBOOK_CONTAINER_NAME} || true && docker rm ${STORYBOOK_CONTAINER_NAME} || true"
+                        sh "docker run -d --name ${STORYBOOK_CONTAINER_NAME} -p 6006:6006 ${DOCKER_STORYBOOK_IMAGE_NAME}"
+                    }
+                }
             }
         }
     }
